### PR TITLE
The board was adding to cells it shouldn't be with #place

### PR DESCRIPTION
**Pull request by jacobmitchinson**
# place was adding one extra cell per ship due to the implementation of #times. We have tested and corrected error. Cheers, Jake and Danielle.

### CODE REVIEW

**Comment by sjmog** [comment]
Nice catch @jacobmitchinson !

**Comment by jacobmitchinson** [comment]
Thanks! It only took you guys 9 months!

**Comment by jacobmitchinson** [comment]
@sjmog

**Comment by sjmog** [comment]
Our CI runs via manual crank ;)

**Pull request merged**
